It's morning
Where are Loopy and Petty
Poby
Who is it
Poby Harry
nbsp
I'm sorry Harry
Poby Harry
nbsp
Hi
nbsp
Hello Sleepy heads
nbsp
nbsp
nbsp
nbsp
You guys Hi
nbsp
Hi
nbsp
Where's your plane
Here we go
nbsp
Hello You're all here
Eddy is this the plane
nbsp
This is going to fly
Yes it is
nbsp
Are you ready
nbsp
Off you go
Wow
Uhh
Oh no
Huh
Huh
Don't be disappointed
nbsp
Tahtah
Wow
WowThis is fantastic
Will it work
nbsp
Are you ready
nbsp
Huh
This time they crashed
This time I'm sure it'll work
You won't crash in to anything
Let's take off
CrongCrongCrong
Pororo your plane
Huh
Huh
Popopo
Huh What is that
Hey Look over there
It's an UFO
We're back
nbsp
Pororo Crong
nbsp
You're safe Huh
nbsp
Who who are they
Ohsay hello
nbsp
nbsp
And this is Pipi
Pipi
They're friends I met
They are
Hmm
Pi
But their plane broke
PipipiPipipi
Popo Pipi
nbsp
I'll make you something to eat
Pipipipi
Now All done
Here you go
nbsp
Pipipi
Like this
Huh
nbsp
nbsp
nbsp
Oh
nbsp
have some more
Pororo and friends and Popo
Hope they all become
I told you not to move
HuhHmmm
nbsp
Okay
Kind of tough hanging there
nbsp
I'll sing a song for you
A song
I'm I'm I'm
nbsp
nbsp
nbsp
Here you are
nbsp
I was singing a song for Poby
Since you're all here
Harry
There're some cookies
nbsp
That sounds good
Cookies
CrongCrong
CrongCrongCrong
nbsp
nbsp
Crong
Hey guys
Here's the cookie
nbsp
Why don't we play tag
Tag Then let me finish
nbsp
Huh Ookay
Here here This way
nbsp
Tag Let's go
Poby come on out
What a relief
Who's going to be it
Wait for me
I wonder
PopopoI Think It's Done
Let's Try It Then
Po Popo
nbsp
Pipipi
Popo
Pipi
Pipipipi
Pipipi
Pipi
it seems like Popo is hungry
Pipi Loppy
Now all done
Oh Loopy made food
Popo and Pipi flew
Where did every one hide
Oops
There he is
Loopy
Pipi
No Body Is Home
nbsp
Cookies
Popo
PoGoodPo
WhatIsThis
Popopo
Pipi Pipi Pipipi
nbsp
nbsp
Pipipipi
PipiStopIt
Pipi
Pipipipi
Pipi
Pipipi Pipipi
Pipi
Pipi I'mSorry
nbsp
Pipipipipi
Pi Pi Pi
Popopopo
Pipipi
nbsp
There Done
Thank You
Poppop
nbsp
The house became a mess
Popo Pipi we'll help
nbsp
Popo Popopo
nbsp
Pipi
nbsp
Pipi
nbsp
Pipipipipi
Popo and Pipi
It's lateat night
nbsp
Finished
Eddy made a robot
Now let's see if it works
Now if I wait a little while
Hmm
it became morning
Eddy
nbsp
CrongCrong
nbsp
Hi
nbsp
You said that you'll show us
Let's go in and see
Wow
Wow
Now let me turn it on
Like this and
Hello
nbsp
Wow It's moving
Hello Eddy
nbsp
Wow it talks
nbsp
nbsp
Show them
nbsp
Let's see
Here I go Fly
Wow
nbsp
Oops
Rody you can't fly
That's right
I can dance like this
Can you fix this then
Let me see that
Umm
What
nbsp
Camera
nbsp
nbsp
My camera broke
Huh Wait a minute
Huh
It's completely broken
I I'll fix this for you
Is there anything
nbsp
Someting I can do well
nbsp
Strong I'm strong
Strong
See I can lift more
I can lift more
nbsp
More more and more
Dangerous
Danger
OhIt's dangerous
I think It's better to go out side
You guys
Huh Wow
I made this
Wow You made it so big
It's really big
See
nbsp
Wow
I can push harder
Watch out Rody
Huh
Oh
Let's show them something else
Someting else
Wait
I better get going
Me too
It became night
Uh Rody
Yes Eddy
Come on sleep with me
In the bed Wow
Yeah Exciting
Rody I can't sleep with you
Can't sleep with me
I'll make a house for you instead
My house
Yes
Wow
Thanks Eddy
nbsp
Many things happened today
But Eddy loves
Wow it looks fantastic
nbsp
nbsp
Wow It's my house
Eddy made a house for Rody
WowHuh
nbsp
Wow
Ohh This is fun
Rody becareful
I'm alright Wow
Oh
I told you to becareful
I should be more careful
nbsp
nbsp
Hello Friends
Congratulations
Here's a present for you
I brought a book
I brought this for you
A mini car
CrongCrong
Here it's a bowtie
Wow Thanks
I can't see Loopy around
You're right
I'm over here
nbsp
Wow
Congratulations
nbsp
The candle
nbsp
With my mouth
You can't blow wind
Rody couldn't blow
Now shall we start eating
Let's
Tastes good
Rody
You can't eat food
I can't eat
nbsp
Huh
Rody tried to drink his milk
Tastes good Huh
Oh Rody spilled milk on his face
I love to play all day
nbsp
Rody you're not supposed
Huh He is waking up
Rody are you alright
What a nice sleep
nbsp
nbsp
Don't eat anything from now on
nbsp
We'll be going now
CrongCrong
Every one went home
nbsp
Bye
Rody was happy to have
The mini car
Let's try it
Huh
Hmm Let's see
This is fun
Fun
Huh
it's Rody's voice
What's Oh
Huh
Eddy are you alright
nbsp
I'm sorry
It's alright
Congratulations again Rody
Eddy Thanks
O okay
nbsp
Rody was really happy
CrongCrong
CrongCrong
CrongCrong
Crong
WowIt's a toy plane
CrongCrongCrong
Crong
Crong
CrongCrong
Want to change
nbsp
No thanks
CrongCrong
Crong
CrongCrongCrong
Pororo
nbsp
You want me to roll the car
Do it yourself
CrongCrongCrong
CrongCrong
Crong
Crong
CrongCrongCrongCrong
Not so fast
Crong Corng
Humph
nbsp
Crong Crong
Crong Crong
Crong Crong
Crong
That's my car
Crong Nah
nbsp
nbsp
nbsp
Stop
Crong
Crong you
Get it
nbsp
Huh You
Crong Crong
Crong took the toy plane
Crong Crong
nbsp
nbsp
nbsp
nbsp
Whide And Deek
Oh Hide And Seek
Huh
Found you
Stop right there
nbsp
Stop
Crong Crong
Crong
nbsp
nbsp
Pororo Crong Huh
Huh
Hmm Huh
Hmm it's a toy plane
CrongCrong Crong
Stop right there
Crong
Crong
You stop right there
Crong Crong
Give me back the plane
nbsp
Huh
You guys
Hello
Huh
Look I found it
Huh That's mine
Huh
It's yours Oh Here
Glad I found it
Crong Crong
Rody also wanted to play
Here Rody
nbsp
nbsp
And Crong can play with it after
I'm sorry about what I did
Let's share our toys
Crong Crong Crong
nbsp
It's more fun when you share
Pororo is going to ride
Everyone is here to see it
I'll be back
CrongCrong
Pororo are you sure about this
Don't worry
CrongCrong
Wow It's flying
See I told you it'll fly
CrongCrong
nbsp
CrongCrong
Be careful Pororo
Don't worry
Wow
Wow Nice
Crong Crong
What is that
Alright
in the deep deep forest
There lived Tongtong the dragon
Cock a doodle doo
Cock a doodle doo
Appear chicken
Let's see
A little chick appeared
Huh Weird
nbsp
nbsp
Huh
Oh Kuri kuri Tongtong
I should have an apple
This looks like the right place
Kuri kuri Tongtong
nbsp
There Huh
Crong
nbsp
Crong
Huh That's my apple
Taking my apple
I can't catch the plane
Kuri kuri Tongtong
Huh Thant's not It
Ah that's right
nbsp
Done
nbsp
Now shall I go
Huh
Why aren't Pororo and Crong
Wait this sound
Oh It's plane
nbsp
Wow It's Pororo
Hmm Huh
Oh Found them
nbsp
What is that
Oh
Here you are
nbsp
Wait
Huh
nbsp
Here I go
What are you doing
nbsp
nbsp
nbsp
Huh
Pipipipi
Who are you
Huh
Pipipipi
What a sneeze Sorry
My name is Tongtong
Oh and this is
I've come to get my apple
nbsp
Crong
Yes That apple is mine
CrongCrong
nbsp
nbsp
I'm sorry I startled you
I'll be going now
Tongtong
Since you've came all the way here
is it alright
Yes
Then are we going to be friends
Yes
nbsp
Tongtong was glad to have
And our friends
But Tongtong will have
Tongtong is showing magic
nbsp
Kurikuri Tongtong
Huh
The cactus turned
Wow
nbsp
nbsp
nbsp
Huh It's the same
Huh
What
nbsp
Oh
nbsp
Kurikuri Tongtong
Wow
Hmm
Kurikuri Tongtong
I should be going home now
Huh Yeah
There
Let's go Ouch
Good bye
OK
Tongtong went back to his house
Huh Harry
nbsp
Harry has disappeared
I'm home
I sometimes make mistakes
You already made
Huh
You want to learn magic
Yes
nbsp
Why not
Only a dragon can use my magic
Aha Then can you make me
Let's see
Yes It's here
Kurikuri Tongtong
Huh It's the same
Try lifting the crystal ball
This Let's see
Oh Wow
Harry really did get stronger
Now you're the strongest bird
nbsp
nbsp
nbsp
Yeah
So I'm the strongest bird
Already there
Get one in
Poby
nbsp
nbsp
Let me help you with that
Thanks but you can't even lift
Wrong This is nothing
Huh
nbsp
Oh no
Um Was I too strong
I think you're better
Oh
Playing ball
It's you Harry
You think
Huh Was I too strong
nbsp
Oh
Hm Huh
The seesaw is not moving
No
Hello
Huh
Let me ride it too
Glad you're here
Yes over here
nbsp
Huh
nbsp
No need for that
Here I go
Uh
Um I I should be going now
Harry seems a bit gloomy
nbsp
Huh
Tongtong
So do you feel great
Harry found out that being strong
Will you change me back to
nbsp
Kurikuri Tongtong
Uh
What is this
That wasn't It Then
Kurikuri Tongtong
Huh What
Hmm Not this one either
Tongtong had to use his magic
What is this
Pororo and friends
Huh
Wow I got one
Wow It's big
Huh
Uh
nbsp
Oh
Huh
Huh
What a tiny fish
nbsp
At least I got a tiny fish
What
That's It I'll show you
nbsp
Pororo what are you going to do
I'm going to catch a big fish
What
Whoa
Here
Crong
I'll bet It's bigger than
Alright
Tah tah
nbsp
Yeap
I'll catch a bigger one
nbsp
Oh no
A fish
You
Stop I'll catch you
The shark is going after Pororo
nbsp
Stop right there
Uh Where did it go Huh
Wow It's big
Get you
Huh
A sh shark
Huh
Pororo is in danger
nbsp
That does It
Er Pororo Run away
Pororo let's get out of here
Almost there Huh
Wait
Go back Or else you're
The friends have rescued
nbsp
You guys
I caught a fish
Huh
nbsp
nbsp
This time Eddy is in danger
Huh
Save me
Eddy run
Huh Rody
Huh
Rody
Are you alright
nbsp
Rody Rody
He's awake
nbsp
You saved Eddy
Thanks Rody
nbsp
Thank goodness
Shark That's what you get
Pororo and friends are
How is it
Eddy made
nbsp
Eddy can I borrow this
Just for a day huh
Hmmm
Thanks
Crong
Crong Crong
So you want it that way huh
Crong
Crong
Put that down
Crong
nbsp
if you're going to fight
We we won't fight
Crong Crong
So Pororo and Crong
Borrowed Eddy's toy
Crong
nbsp
Crong
Crong Crong
nbsp
I'll move it from here
Crong
Crong Crong
nbsp
Crong Crong Crong
That's it
Crong Crong
Crong
Crong
Alright
Crong
I turned it off
nbsp
Catch it if you can
nbsp
nbsp
Crong
Crong
Crong
Crong
Crong Crong
Crong Crong Crong
Crong Croro
Oh dear Crong went outside
nbsp
I'm I'm I'm
nbsp
Ummm
Poby
nbsp
I'm singing for you
i I'm sorry
Crong
Huh
Crong
nbsp
Crong Crong
Pororo wasn't having fun playing
Crong Crong
Crong Crong
Where did he go
Pororo went running out
Pororo Huh
He's not home
Crong
Crong
Bye
nbsp
nbsp
Pororo
You guys
have you seen Crong
nbsp
Crong was worried about Pororo
Cororo
Pororo
Pororo
Huh
nbsp
Huh It's Crong
Crong
Crong Where were you
nbsp
No matter how many times
Pororo and Crong
The friends are gathered
Loopy is baking delicious cookies
Wait a little longer and
nbsp
Crong Crong
How about telling tales
Yes I have one to tell
Long long ago in an ice land
nbsp
nbsp
nbsp
What Princess Loopy
It's just an old tale
Humph
It's time my princesses
Your Majesty
nbsp
who brings me the most
is that so
Then you will marry the prince
who brings the most
So all the princes of
nbsp
First Guest
What did you bring
I have brought a one
A robot
nbsp
Um
Rody
Errr isn't it interesting
Guards
Yes Pipipipipi
Well good bye then
Second Guest
Prince Tongtong
I have brought a magic crystal
Wow That's interesting
Crystal ball
Snow white is the fairest
What
W wait a minute
Who is the fairest in the world
The fairest is Snow oop
Try asking something else
That's OK Humph
You may go now
nbsp
Third Guest is
nbsp
Wow A violin
This is a magic violin
Oh yes Oh
Oh What is this
nbsp
Oh Guards
Yes Pipipipipi
Let the next guest come in
nbsp
Fifth Guest is
nbsp
And what is that
Huh
Crong Crong
As Prince Crong opened the box
nbsp
Oh Guards
Take that man out of here
nbsp
Crong
The Last Guest
nbsp
Oh That's something
It's a plane
Then can I ride it
nbsp
Wow How exciting
I'm back Your Majesty
How was it flying
it was very interesting
Um
nbsp
Prince Pororo may
nbsp
Why
But I want to marry
What Humph
Wow Cookies
Looks delicious
Wait
Answer my question
Who's the fairest
Um Loopy
nbsp
nbsp
Oh no
You are all wrong
The correct answer is
That's right
The friends are going to
On Pororo's team
nbsp
Crong
Poby
Loopy
and Tongtong as the goal keeper
And on Eddy's team Eddy
nbsp
nbsp
Pipi
and Popo as the goal keeper
Play ball
Crong Catch
CrongCrong
Err I'm here to block
Crong
Here it goes
Popo
Goal
CrongCrong
Pororo's team is winning 1 :0
I Am Sorry
nbsp
Eddy Catch
Alright Here goes
I got him
Left
nbsp
Oh I'm tired
Give it to me
nbsp
Get it
nbsp
Oh that's pretty
nbsp
Here I come
Huh
The ball that Rody kicked hit
Oh
Huh
Pororo's team is winning 2:0
Yeah
nbsp
Now we have to block
Okay
Let's continue to play ball
Huh
Pipi flew up and blocked the ball
That way
Huh
This time Rody suddenly turned tall
I got it
Huh
Goal
Eddy's team made a goal
Nice job Rody
That was nothing
Let's go
Stop him
The Shark started
Crong Here
Crong
Crong
Popopopo
Rody
Wait
I got it
That's mine
nbsp
Eddy's team scored again
Okay
Alright Here goes
nbsp
Huh
Pipi blocked Pororo's balls
Pipi
Pipipipipi
nbsp
Oh
Here I go
Kurikuri Tongtong
This time Tongtong got larger
Rody
Okay
The ball is flying too far
Oh dear the shark
The friends had to finish
instead the shark had a great time
It's morning
There's Popo and Pipi's spaceship
Popo is fixing the spaceship
Popo
nbsp
Um It Will Fly Anyways
nbsp
Pipipipi
Do You Want To Try it
nbsp
You Are Sure It Is Fixed
I'm Sure
OK Beep
Oh
You Said That You Fixed It
That Is Strange
Pipipipi
Oh
Po Po You
nbsp
Huh
Hi we're here
HelIo
Wow
nbsp
Oh
What kind of a tree is that
It's A Tree From Space
Here
Wow
Now Let Me Show
When The Light Is Gone
When It Is Dark
Wow
Wow We're in space
CrongCrong
nbsp
Don't you wanna go back
Yes I Want To Go
Eddy
Oops
Wait I'll sing a song to
nbsp
Barabarabarabarabam Barabara
nbsp
nbsp
Popo Pipi
nbsp
You will
Umm
Of course
Um
It's looks finished
Really
nbsp
is this the control handle
Pipipi
The space ship is flying
Wow
Shall we go on a test flight
Huh This isn't working
The space ship fell
nbsp
nbsp
What was the problem
Huh
Eddy are you done fixing it
No It's not done yet
nbsp
By night time Eddy was finished
Finished
Really
nbsp
Why do I feel like
Eddy What's going on
nbsp
This time the space ship
The Space
nbsp
I'm so sorry
nbsp
nbsp
You Were Only Trying
nbsp
nbsp
That's Right
We'll all help you fix it next time
Thanks
Although the spaceship was broken
nbsp
Today Eddy is helping Popo
Umm Okay
Finished
I fixed it
Pipi try flying it
Huh Oh OK
Pi pipipi
It's Fl Flying
It's Really Flying
Wow
You did it Eddy
Popo Pipi Congratulation
nbsp
You can go back home now
Yes
Let's get off
We Will Be Going Back
Yes
Crong
There are friends waiting
Crong Crong
Good bye
We Had A Great Time
It's time to say good bye
nbsp
nbsp
Wait a minute
Pi
Here Home made cookies
Thank You Loopy
Come and visit us
We Will
Bye
Bye
Popo and Pipi's space ship
Flew up to go outer space
nbsp
Pipi Pipi
Wow
nbsp
They finially arrived
Popo
Popo Pipipipipi
Popo and Pipi finially
nbsp
Popopo Pi
Try it
Pipi
Popopopo
Pipi Pipipi Pipipi Piri Piri
Oh dear they have eaten away
Hope they're safe
Pororo and friends are
Do you think Popo and Pipi
They should have
Boring
Crong
Crong Crong Popo Pipi Crong
Huh
Crong
Oh That's
Popo and Pipi
Wow
Pipipipi Pipipipipi
Good to have you back
Thank You Pororo
nbsp
Every Body come Out
These are my friends
Hello
Oh that
The cookies that you had were
nbsp
Popopopo Pipipipipipi
Why What's going on
They Said Your Cookies Were
Really Wait
Who wants to have some cookies
Loopy's cookies are fantastic
it brought Popo and Pipi back
And helped bring new friends
